FROM node:10

# Env
ENV GO_DADDY_API_KEY=9jX8AQBrux3_VWF4Np2NTLvYXfb5Y4pLoH
ENV GO_DADDY_API_SECRET=VWF9RAdEW2Ld6mXFsuXEVu
ENV GO_DADDY_CUSTOMER_ID=46523510
ENV GO_DADDY_DOMAIN=jasontalon.com
ENV CRON_DURATION_MINUTE=30

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . /usr/src/app

RUN npm start tsc

EXPOSE 8080

CMD [ "npm", "start" ]